### ISSUE TITLE
eth_sendRawTransaction rejects 1559 transactions

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3-server#25]
the problem is this regex that is used:

https://github.com/blockchainsllc/in3-server/blob/b9b1f24c396272602676f30ceef9e76755d38ad3/src/types/rpc.yaml#L279

so for valid 1559 transactions it fails with:

`{"id":1,"error":{"code":-32602,"message":"eth_sendRawTransaction : params[0] should match pattern \"^0x(0|[a-fA-F1-9]+[a-fA-F0-9]*)$\""},"jsonrpc":"2.0"}`

**Comment by simon-jentzsch** [comment]
oh.. thanks, just fixed it. I will push out a bug-fix now..

**Comment by ligi** [comment]
thanks so much!
and while I have your attention: any chance eth_feeHistory could be exposed? currently I get Method not found for this

**Comment by ligi** [comment]
created this issue for feeHistory: https://github.com/blockchainsllc/in3-server/issues/26
any info when the sendRawTransaction change will be rolled out to nodes?

**Comment by ligi** [comment]
unfortunately I think we need to reopen this one. Even though the regex now does not seem to be the problem anymore I am getting a different error now:

```
✓ ~ curl -X POST -H  "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x02f86a0507849502f900849502f90582520894381e247bef0ebc21b6611786c665dd5514dcc31f8080c001a04c23103dda68fc3287b9972f0b105752e8c79e6f3135ba631db65102202a563fa07a3c44a30ac5aa24f5e259317bda094fb594d652c8808e72d7557f6457f9ed27"],"id":1}' https://in3-v2.slock.it/goerli/nd-1
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32602,"message":"Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length."},"stats":null,"in3":{"lastValidatorChange":0,"lastNodeList":5339558,"execTime":10,"rpcTime":9,"rpcCount":1,"currentBlock":5346459,"version":"2.1.0"}}
```

a bit weird though - it is 0x prefixed and has a even length


also sending it to a dappnode with no problem:
```
✓ ~ curl -X POST -H  "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x02f86a0507849502f900849502f90582520894381e247bef0ebc21b6611786c665dd5514dcc31f8080c001a04c23103dda68fc3287b9972f0b105752e8c79e6f3135ba631db65102202a563fa07a3c44a30ac5aa24f5e259317bda094fb594d652c8808e72d7557f6457f9ed27"],"id":1}' http://goerli-geth.dappnode:8545
{"jsonrpc":"2.0","id":1,"result":"0x9b66419b1484b0045fe457adb63a377e09d7bb6a4ea57f93c9d8bf94f7dc4f29"}
```
