### ISSUE TITLE
support eth_feeHistory

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3-server#26]
currently I get this error for eth_feeHistory:

```json
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32601,"message":"Method not found"},"stats":null,"in3":{"lastValidatorChange":0,"lastNodeList":5331392,"execTime":8,"rpcTime":8,"rpcCount":1,"currentBlock":5334421,"version":"2.1.0"}}
```

would be really great if in3-server could support that method

**Comment by leonardotc** [comment]
Hello Ligi,

I might be wrong on this but I think the method is already supported. Maybe the actual ethereum client needs updating since that error seems to have passed through the internal validation. I will check it out to have a more concrete answer.

**Comment by ligi** [comment]
thanks! I tried:  https://in3-v2.slock.it/goerli/nd-1 - and this is where I get the "Method not found"

**Comment by ligi** [comment]
oh - now it seems to work - thanks for whatever you did ;-)

**Comment by leonardotc** [comment]
No problem. That ethereum client was outdated (the mainnet boot nodes should support it too).

**Comment by ligi** [comment]
great! did you see #27 ? This is kinda blocking me now
