### ISSUE TITLE
stats only work for mainnet

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3-server#8]
but not for e.g. goerli:

https://in3.slock.it/?n=goerli

![image](https://user-images.githubusercontent.com/111600/66692620-25579300-ecdb-11e9-8ada-5b9eb6caad5f.png)

should work as they are linked like this here: https://in3.readthedocs.io/en/develop/getting_started.html

**Comment by pasDamola** [comment]
Hi @ligi how do I begin to work on this. The issue is not really clear.
Thanks

**Comment by ligi** [comment]
When clicking on he link I see something like this:
![image](https://user-images.githubusercontent.com/111600/68079347-94805d00-fe2b-11e9-83de-fab2f3c344db.png)

but I expect to see the actual stats

**Comment by junaidev** [comment]
Now you should be able to select Goerli using Preferences dialog box ( Top right gear icon > Preferences Dialog > Select Goerli ) https://in3.slock.it/
