### ISSUE TITLE
deployNodeRegistry may fail if chain reorg happens

### ISSUE THREAD

**Issue by Troublor** [blockchainsllc/in3-server#9]
The deployNodeRegistry function defines as follows: 
```javascript
export async function deployNodeRegistry(pk: PK, url = 'http://localhost:8545', transport?: Transport) {

  const blockHashAddress = await deployBlockhashRegistry(pk, url, transport)
  const erc20 = await deployERC20(pk, url, transport)
  const regData = await deployRegistryData(pk, url, transport)
  const registry = await tx.deployContract(url,
    '0x' + in3ContractBin.contracts[Object.keys(in3ContractBin.contracts).find(_ => _.indexOf('/contracts/NodeRegistryLogic.sol:NodeRegistryLogic') >= 0)].bin
    + toHex(blockHashAddress, 32).substr(2)
    + toHex(regData, 32).substr(2)
    + toHex('2386f26fc10000', 32).substr(2)
    , {
      privateKey: pk,
      gas: 8000000,
      confirm: true
    }, transport)
    .then(_ => toChecksumAddress(_.contractAddress) as string)

  await tx.callContract(url, regData, 'adminSetSupportedToken(address)', [erc20], { privateKey: pk, gas: 500000, confirm: true, value: 0 }, transport)
  await tx.callContract(url, regData, 'adminSetLogic(address)', [registry], { privateKey: pk, gas: 500000, confirm: true, value: 0 }, transport)
  return registry
}
```

In a special situation that Ethereum chain reorg happens (i.e. the transaction that deploy ERC20 and  the transaction that deploy RegistryData are included in two sibling blocks and the block containing the second transaction becomes part of canonical chain), then `adminSetSupportedToken(address)` may store an invalid contract address. Although all these transactions above are executed without any failure, any transactions later on which depends on the ERC20 contract address will end up in failure because ERC20 contract doesn't exist anymore due to chain reorg. 

The code here doesn't take this scenario into consideration, but it is defect which can lead to unexpected behaviour in practice.

**Comment by simon-jentzsch** [comment]
Currently the deployNodeRegistry is only used in order to run the integration-tests. Here we are running a dev-chain in parity and simply deploy the contracts before running the tests. 

For the production, we are actually using CI-scripts that set up the contracts on mainnet. (triggered manually)

In order to handle reorgs, you would actually need to wait enough blocks to reach finality before sending the next transaction.
